#  EPILEPTIC  SEIZURE RECOGNITION

# Load important libraries

In [2]:
import numpy as np
import pandas as pd

# Load dataset

In [3]:
df=pd.read_csv("data.csv")

In [4]:
df.head()

Unnamed: 0   X1   X2   X3   X4   X5   X6   X7   X8   X9  ...  X170  X171  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33  ...   -17   -15   
1  X15.V1.924  386  382  356  331  320  315  307  272  244  ...   164   150   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85  ...    57    64   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87  ...   -82   -81   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21  ...     4     2   

   X172  X173  X174  X175  X176  X177  X178  y  
0   -31   -77  -103  -127  -116   -83   -51  4  
1   146   152   157   156   154   143   129  1  
2    48    19   -12   -30   -35   -35   -36  5  
3   -80   -77   -85   -77   -72   -69   -65  5  
4   -12   -32   -41   -65   -83   -89   -73  5  

[5 rows x 180 columns]

# Remove first column and make last has binary clasification(0 or 1)

In [5]:
df["OUTPUT_LABEL"] = df.y == 1
df["OUTPUT_LABEL"] = df["OUTPUT_LABEL"].astype(int)
df.pop('y')
df.drop(df.columns[0], axis=1, inplace=True)

In [6]:
df.head()

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10  ...  X170  X171  X172  \
0  135  190  229  223  192  125   55   -9  -33  -38  ...   -17   -15   -31   
1  386  382  356  331  320  315  307  272  244  232  ...   164   150   146   
2  -32  -39  -47  -37  -32  -36  -57  -73  -85  -94  ...    57    64    48   
3 -105 -101  -96  -92  -89  -95 -102 -100  -87  -79  ...   -82   -81   -80   
4   -9  -65  -98 -102  -78  -48  -16    0  -21  -59  ...     4     2   -12   

   X173  X174  X175  X176  X177  X178  OUTPUT_LABEL  
0   -77  -103  -127  -116   -83   -51             0  
1   152   157   156   154   143   129             1  
2    19   -12   -30   -35   -35   -36             0  
3   -77   -85   -77   -72   -69   -65             0  
4   -32   -41   -65   -83   -89   -73             0  

[5 rows x 179 columns]

In [7]:
non_seizure, seizure = df["OUTPUT_LABEL"].value_counts()
print('The number of trials for the non-seizure class is:', non_seizure)
print('The number of trials for the seizure class is:', seizure)


The number of trials for the non-seizure class is: 9200
The number of trials for the seizure class is: 2300


# It is unbalanced dataset  

In [8]:
print("Percentage of seizure is: ",100*((seizure)/(seizure+non_seizure)))
print("Percentage of non-seizure is: ",100*((non_seizure)/(seizure+non_seizure)))

Percentage of seizure is:  20.0
Percentage of non-seizure is:  80.0


In [8]:
df.shape

(11500, 179)

In [9]:
X = df.iloc[:,0:178].values
X.shape

(11500, 178)

In [10]:
Y=df["OUTPUT_LABEL"]
Y.shape

(11500,)

# Spilt dataset into train ,test 

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [12]:
X = StandardScaler().fit_transform(X)

In [15]:
X

array([[ 0.88505134,  1.20992878,  1.46276429, ..., -0.63414367,
        -0.43329036, -0.23539922],
       [ 2.40057718,  2.36619038,  2.23944096, ...,  1.02342937,
         0.95424076,  0.85653664],
       [-0.12328657, -0.16915405, -0.22513147, ..., -0.13687176,
        -0.13859348, -0.14440456],
       ...,
       [ 0.1544592 ,  0.10184476, -0.01720228, ...,  0.0657205 ,
         0.07015014,  0.02545213],
       [-0.17159018, -0.08484331,  0.00725997, ...,  0.49546166,
         0.43852123,  0.40762968],
       [ 0.24502848,  0.31262161,  0.41088722, ...,  0.0657205 ,
         0.08856869,  0.19530882]])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3,random_state=10)

# Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression
ir=LogisticRegression(C=1e5)
ir.fit(X_train,y_train)



C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=100000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
y_pred=np.array(ir.predict(X_test))

In [21]:
Y=np.array(y_test)

In [22]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [23]:
print(confusion_matrix(y_test,y_pred))

[[2755    7]
 [ 599   89]]


In [24]:
print(accuracy_score(y_test,y_pred))

0.8243478260869566


In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      1.00      0.90      2762
           1       0.93      0.13      0.23       688

    accuracy                           0.82      3450
   macro avg       0.87      0.56      0.56      3450
weighted avg       0.84      0.82      0.77      3450



# RandomForest 

In [27]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [28]:
y_pred=clf.predict(X_test)

In [29]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9756521739130435


In [30]:
print(confusion_matrix(y_test,y_pred))

[[2720   42]
 [  42  646]]


In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      2762
           1       0.94      0.94      0.94       688

    accuracy                           0.98      3450
   macro avg       0.96      0.96      0.96      3450
weighted avg       0.98      0.98      0.98      3450



# Naive Bayes 

In [32]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

In [33]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9588405797101449


In [34]:
print(confusion_matrix(y_test,y_pred))

[[2685   77]
 [  65  623]]


In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.97      2762
           1       0.89      0.91      0.90       688

    accuracy                           0.96      3450
   macro avg       0.93      0.94      0.94      3450
weighted avg       0.96      0.96      0.96      3450



# KNN 

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [43]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9266666666666666


In [44]:
print(confusion_matrix(y_test,y_pred))

[[2758    4]
 [ 249  439]]


In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96      2762
           1       0.99      0.64      0.78       688

    accuracy                           0.93      3450
   macro avg       0.95      0.82      0.87      3450
weighted avg       0.93      0.93      0.92      3450

